default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: polak
  database: shortify_development

test:
  <<: *default
  database: shortify_test
  username: polak
  password: ''
  timeout: 5000
  host: <%= ENV.fetch("RAILS_TEST_HOST_NAME") { '' } %>
